# Generated by Django 4.2.7 on 2023-11-27 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diary',
            options={'verbose_name_plural': '日記'},
        ),
        migrations.RenameField(
            model_name='diary',
            old_name='email',
            new_name='user',
        ),
    ]
