# Generated by Django 4.2.7 on 2023-11-30 03:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PregnantMomsHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregnancy_week', models.IntegerField(default=20, verbose_name='妊娠週')),
                ('my_date', models.DateField(default=django.utils.timezone.now, verbose_name='')),
                ('height', models.FloatField(default=150, verbose_name='身長')),
                ('weight', models.FloatField(default=55, verbose_name='体重')),
                ('blood_pressure_upper', models.IntegerField(default='100', verbose_name='血圧(上)')),
                ('blood_pressure_under', models.IntegerField(default='50', verbose_name='血圧(下)')),
                ('waist', models.FloatField(default=85, verbose_name='腹囲')),
                ('fundall_length', models.FloatField(default=20, verbose_name='子宮底長')),
                ('edema', models.CharField(blank=True, choices=[('－', '－'), ('＋', '＋'), ('＋＋', '＋＋')], max_length=10, verbose_name='浮腫')),
                ('unrine_protein', models.CharField(blank=True, choices=[('－', '－'), ('＋', '＋'), ('＋＋', '＋＋')], max_length=10, verbose_name='尿蛋白')),
                ('diabetes', models.CharField(blank=True, choices=[('－', '－'), ('＋', '＋'), ('＋＋', '＋＋')], max_length=10, verbose_name='血糖')),
                ('other_test', models.TextField(blank=True, max_length=1000, verbose_name='他検査,特記事項など')),
                ('user', models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name_plural': '妊娠中',
            },
        ),
        migrations.CreateModel(
            name='MomsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField(default=150, verbose_name='身長')),
                ('blood_tipe', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('O', 'O'), ('AB', 'AB')], max_length=10, verbose_name='血液型')),
                ('rh_tipe', models.CharField(blank=True, choices=[('＋', '＋'), ('－', '－')], max_length=10, verbose_name='Rh型')),
                ('check_1', models.DateField(blank=True, verbose_name='不規則抗体')),
                ('check_2', models.DateField(blank=True, verbose_name='子宮頸がん検診')),
                ('check_3', models.DateField(blank=True, verbose_name='梅毒血清検診')),
                ('check_4', models.DateField(blank=True, verbose_name='HBs抗原')),
                ('check_5', models.DateField(blank=True, verbose_name='HCV抗体')),
                ('check_6', models.DateField(blank=True, verbose_name='HIV抗体')),
                ('check_7', models.DateField(blank=True, verbose_name='風しんウィルス抗体')),
                ('check_8', models.DateField(blank=True, verbose_name='HTLV-1抗体')),
                ('check_9', models.DateField(blank=True, verbose_name='クラミジア抗原')),
                ('check_10', models.DateField(blank=True, verbose_name='B群溶血性連鎖球菌')),
                ('user', models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name_plural': '母親基本情報',
            },
        ),
    ]
